### ISSUE TITLE
missing literature evidence due to EFO synonyms not covering roman numerals

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/platform_semantic#2]
Can we add Mucolipidosis type IV as a synonym for Mucolipidosis type 4. 

In addition do we know if EFO have roman numeral covered in all the synonyms?

On 06/03/2017 17:12, Şenay Kafkas wrote:
> Hi,
>
> Our dictionary based tool is aware of
> -greek letters and symbols
> -plural singular forms
> -lower case/ upper case of the first character of a given term
>
> only. If you realise any synonyms that our tool cannot detect, you can directly contact Sira and make a request to add it to EFO. Once it is added to the EFO, our tool will be able to annotate it.
>
> Thanks
> Senay
>
> On 06/03/17 17:05, Chuang Kee Ong wrote:
>>
>>

**Comment by elipapa** [comment]
Issue moved to [opentargets/epics #120](https://github.com/opentargets/epics/issues/120) via [**ZenHub**](https://www.zenhub.com/)
